version: '2'
services:
  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'

    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_HOST: 0.0.0.0
       MYSQL_ROOT_PASSWORD: minishop_root_password
       MYSQL_DATABASE: minishop
       MYSQL_USER: minishop_user
       MYSQL_PASSWORD: minishop_password
